export const TRACKS_ACTIONS = {
  GET_TRACKS: 'GET_TRACKS',
  SET_TRACKS: 'SET_TRACKS',
  SET_CURRENT_TRACKS_TYPE: 'SET_CURRENT_TRACKS_TYPE',
  SET_TRACKS_TYPES: 'SET_TRACKS_TYPES',
  TOGGLE_PLAYING: 'TOGGLE_PLAYING',
  SET_CURRENT_TRACK: 'SET_CURRENT_TRACK',
  GET_PLAYBACK_DATA: 'GET_PLAYBACK_DATA',
  SET_PLAYBACK_DATA: 'SET_PLAYBACK_DATA',
};
