# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyApp

  pod 'GoogleSignIn'

  target 'MyApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-youtube', :path => '../node_modules/react-native-youtube'

  end

  target 'MyAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
