export const AUTH_ACTIONS = {
  LOGOUT: 'LOGOUT',
  SET_USER: 'SET_USER',
  SET_CHUNE_TOKEN: 'SET_CHUNE_TOKEN',
  SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_UP_REQUEST: 'SING_UP_REQUEST',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SET_SPOTIFY_TOKEN: 'SET_SPOTIFY_TOKEN',
};
